apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-recommendation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cx-recommendation-api
  template:
    metadata:
      labels:
        app: cx-recommendation-api
    spec:
      containers:
        - name: cx-recommendation-api
          image: 396608814647.dkr.ecr.ap-southeast-1.amazonaws.com/cxhack24/recommendation-api:v1.1.0
          ports:
            - containerPort: 3000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-personalize-runtime-config
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-personalize-runtime-config
                  key: secret-access-key
            - name: AWS_REGION
              value: ap-southeast-1
            - name: RECOMMENDER_ARN
              value: arn:aws:personalize:ap-southeast-1:396608814647:recommender/cxhack24-personalize-recommender-top-picks-sg-dev
            - name: FILTER_ARN
              value: arn:aws:personalize:ap-southeast-1:396608814647:filter/cxhack24-personalize-items-available_this_month-filter-sg-dev
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"