apiVersion: v1
kind: Service
metadata:
  name: cx-recommendation-api
spec:
  selector:
    app: cx-recommendation-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer